version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  install:
    commands:
        - npm install
        - - aws cloudformation package --template-file template.yml --s3-bucket github-lambda-demo --output-template-file NewSamTemplate.yml

artifacts:
  files:
      - '**/*'
  #discard-paths: yes
  #base-directory: location
