AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  githublambdademoproduction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: ''
      MemorySize: 1536
      Timeout: 300
      Role: >-
        arn:aws:iam::377117578606:role/brkc-github-lambda-demo-ResizeFunctionRole-1J90QY1PLMNQB
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /MyResource
            Method: ANY
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:*'
      Environment:
        Variables:
          BUCKET: sir-foo-52857c5f58zj
          URL: 'http://sir-foo-52857c5f58zj.s3-website-us-east-1.amazonaws.com'
  Bucket1:
    Type: 'AWS::S3::Bucket'
